### ISSUE TITLE
PL2303HXA.  Phaesd out since 2012. Please contact your supplier.

### ISSUE THREAD

**Issue by timlaverty** [microsoft/farmbeatsforstudents#1]
Using the retail kit, when I click Connect a Device in the Data Streamer tab in Excel I see this in the dropdown.  

Using a different usb serial cable (from the dev prototype kit) it functions.  Is there a way to verify cables?

**Comment by damyka** [comment]
Windows 10 drivers are out of date and need to be updated by the manufacturer in Windows Update. They have been notified.

The workaround is to download and reinstall the drivers manually.
1. Access the link below to download this driver according to the manufacturer:
http://www.prolific.com.tw/US/ShowProduct.aspx?p_id=225&pcid=41
2. After completing the driver download, extract the zipped file;
3. Press Windows + X and select Device Manager;
4. Navigate to the USB device and right-click on it, select Properties;
5. Click the Driver tab> update Driver> Search Computer for Drivers> Browse fmy computer for drivers;
6. Navigate to the folder of the driver you downloaded in step 1.

**Comment by timlaverty** [comment]
thanks!

**Comment by damyka** [comment]
UPDATE:
The above solution works for the Prolific chip. If the Serial-TTL cable has the CH340 chip then follow these instructions:

1. Download the driver utility from the **LINK TO FILE** section of this page: [http://deviceinbox.com/drivers/752-usb-serial-ch340.html](url) 
2. Extract USB_CH341SER.ZIP
3. Navigate to USB_CH341SER\CH341SER\ and run setup.exe

Note that installation of drivers requires elevated permissions. On school computers you may need to contact your IT administrator.

**Comment by minhaj6** [comment]
> reinstall the drivers manually.

it seems that i have to do this every time i restart the windows machine. is there any way to make this change permanent.

**Comment by szlovak** [comment]
> > reinstall the drivers manually.
> 
> it seems that i have to do this every time i restart the windows machine. is there any way to make this change permanent.

Yes , there is:

pnputil /enum-drivers    lists existent drivers

pnputil /delete-driver name.inf   deletes bad driver

**Comment by canalqb** [comment]
Solved New
https://canalqb.blogspot.com/2024/01/windows-10-sunixs-uts2009b-resolvendo.html

**Comment by cino893** [comment]
For Old Chinesse PL2303 this driver is working on Windows 11:

[China Driver PL2303 USB-RS232.zip](https://github.com/user-attachments/files/19494349/China.Driver.PL2303.USB-RS232.zip)

After installation you have to manually pick it from device manager
