### ISSUE TITLE
Script fails if the zip package is not installed

### ISSUE THREAD

**Issue by gnolanccgs** [microsoft/farmbeatsforstudents#3]
Running this on a clean install of Raspberry Pi OS (Buster) fails near the end of the installation process because zip isn't installed by default and the error message for this is not repeated at the end of the installation process making it slightly confusing that the expected output image file is missing. If the script could include a contingency to install missing dependencies this would be helpful.

**Comment by damyka** [comment]
Thank you @gnolanccgs for pointing this out. I will make a note in the readme and will look into adding this to the bash script.

**Comment by gnolanccgs** [comment]
Thank you for this! Other than this minor issue I'm pleased to report that the script does a fantastic job.

**Comment by damyka** [comment]
@gnolanccgs, I have [updated the readme](https://github.com/microsoft/farmbeatsforstudents/commit/aef07f95c9b9eb07b3041f457080b3fbd5ff6f68) and added a [check/install](https://github.com/microsoft/farmbeatsforstudents/commit/a4b569b9362c6dd81164698cf11bd17ddcbed356) for the missing dependency. 

Thanks again for the feedback!

**Comment by gnolanccgs** [comment]
@damyka, thank you very much for fixing this issue. I'm glad to be of some assistance. Closing this as there doesn't appear to be any further action required. All the best!
