### ISSUE TITLE
The current SD card image releases is no longer available

### ISSUE THREAD

**Issue by VeggieVampire** [microsoft/farmbeatsforstudents#4]
When you go to, "https://aka.ms/fbfsimage" it states the files are no longer available. 

![image](https://user-images.githubusercontent.com/4420102/136888739-2f03d22f-8b36-44d1-bb58-f7596599d3a4.png)

**Comment by damyka** [comment]
Thanks @VeggieVampire, I appreciate you bringing this up.

The link to the release is here: [https://github.com/microsoft/farmbeatsforstudents/releases/tag/v1.0.0](https://github.com/microsoft/farmbeatsforstudents/releases/tag/v1.0.0)

The link [https://aka.ms/fbfsimage](https://aka.ms/fbfsimage) now points to: [https://github.com/microsoft/farmbeatsforstudents/releases/download/v1.0.0/FarmBeatsForStudents.v1.0.0.img.zip](https://github.com/microsoft/farmbeatsforstudents/releases/download/v1.0.0/FarmBeatsForStudents.v1.0.0.img.zip)
